package pe.apptrabajador;
import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;
public class MainActivity extends Activity{
 LinearLayout body; int blue=Color.rgb(20,112,235),ink=Color.rgb(18,31,53),muted=Color.rgb(101,116,139),green=Color.rgb(16,185,129),orange=Color.rgb(249,115,22); TextView money,hours;
 int dp(float x){return(int)(x*getResources().getDisplayMetrics().density+.5f);} void bg(View v,int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));v.setBackground(g);}
 TextView t(String s,int z,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(ink);v.setPadding(dp(4),dp(6),dp(4),dp(6));if(b)v.setTypeface(null,1);return v;}
 LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(14),dp(16),dp(14));bg(c,Color.WHITE,18);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(12));c.setLayoutParams(p);return c;}
 public void onCreate(Bundle b){super.onCreate(b);home();}
 void shell(String title,int tab){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(246,249,253));ScrollView s=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(16),dp(12),dp(16),dp(18));s.addView(body);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));LinearLayout nav=new LinearLayout(this);nav.setPadding(dp(3),0,dp(3),0);String[] a={"⌂\nInicio","▣\nCalendario","▤\nHistorial","⚙\nAjustes"};for(int i=0;i<4;i++){Button x=new Button(this);x.setText(a[i]);x.setTextSize(11);x.setAllCaps(false);x.setTextColor(i==tab?blue:muted);x.setBackgroundColor(Color.WHITE);final int q=i;x.setOnClickListener(v->{if(q==0)home();if(q==1)calendar();if(q==2)history();if(q==3)settings();});nav.addView(x,new LinearLayout.LayoutParams(0,dp(62),1));}root.addView(nav);setContentView(root);}
 void home(){shell("",0);LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);LinearLayout tt=new LinearLayout(this);tt.setOrientation(LinearLayout.VERTICAL);tt.addView(t("Hola, Sandra 👋",28,true));TextView date=t(new SimpleDateFormat("EEEE d 'de' MMMM",new Locale("es","PE")).format(new Date()),15,false);date.setTextColor(muted);tt.addView(date);top.addView(tt,new LinearLayout.LayoutParams(0,-2,1));TextView bell=t("🔔   👷",25,false);top.addView(bell);body.addView(top);
 LinearLayout reg=card();reg.addView(t("◷  Registro de hoy                                      Editar",17,true));LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER);String[] z={"☀\nEntrada\n07:30","🌇\nSalida\n17:30","☕\nDescanso\n01:00 h"};for(String q:z){TextView v=t(q,15,true);v.setGravity(Gravity.CENTER);bg(v,Color.rgb(247,249,252),13);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(86),1);p.setMargins(dp(3),dp(5),dp(3),0);r.addView(v,p);}reg.addView(r);body.addView(reg);
 LinearLayout earn=card();bg(earn,blue,20);TextView et=t("▣  Ganancia estimada de hoy",16,false);et.setTextColor(Color.WHITE);earn.addView(et);money=t("S/ 126.40",36,true);money.setTextColor(Color.WHITE);earn.addView(money);TextView up=t("↗  +12% que ayer (S/ 112.80)",13,true);up.setTextColor(Color.rgb(220,255,235));earn.addView(up);body.addView(earn);
 LinearLayout vars=card();vars.addView(t("ⓢ  Ingresos variables (opcional)              + Agregar",17,true));vars.addView(row("🍴","Propinas","Monto de hoy","S/ 42.00"));vars.addView(row("▥","Comisión","Monto de hoy","S/ 18.00"));body.addView(vars);
 LinearLayout inc=card();inc.addView(t("▥  Mis ingresos                         Últimos 4 meses",17,true));LinearLayout bars=new LinearLayout(this);bars.setGravity(Gravity.BOTTOM);int[] hs={70,105,145,115};String[] ms={"Ago\nS/ 2,450","Sep\nS/ 2,910","Oct\nS/ 3,240","Nov\nS/ 2,980"};for(int i=0;i<4;i++){LinearLayout col=new LinearLayout(this);col.setGravity(Gravity.BOTTOM|Gravity.CENTER_HORIZONTAL);col.setOrientation(LinearLayout.VERTICAL);Space sp=new Space(this);bg(sp,i==2?blue:Color.rgb(126,196,247),8);col.addView(sp,new LinearLayout.LayoutParams(dp(48),dp(hs[i])));TextView m=t(ms[i],11,i==2);m.setGravity(Gravity.CENTER);col.addView(m);bars.addView(col,new LinearLayout.LayoutParams(0,dp(190),1));}inc.addView(bars);body.addView(inc);}
 LinearLayout row(String icon,String title,String sub,String val){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.setPadding(0,dp(8),0,dp(8));TextView i=t(icon,22,false);r.addView(i);LinearLayout m=new LinearLayout(this);m.setOrientation(LinearLayout.VERTICAL);m.addView(t(title,15,true));TextView s=t(sub,12,false);s.setTextColor(muted);m.addView(s);r.addView(m,new LinearLayout.LayoutParams(0,-2,1));r.addView(t(val+"  ›",16,true));return r;}
 void calendar(){shell("",1);TextView h=t("Calendario",22,true);h.setGravity(Gravity.CENTER);body.addView(h);LinearLayout c=card();c.addView(t("‹                 Septiembre 2026                 ›",18,true));GridLayout g=new GridLayout(this);g.setColumnCount(7);String[] ds={"L","M","X","J","V","S","D"};for(String d:ds){TextView x=t(d,12,false);x.setGravity(Gravity.CENTER);g.addView(x,new ViewGroup.LayoutParams(dp(45),dp(35)));}for(int i=1;i<=30;i++){TextView x=t(""+i,14,false);x.setGravity(Gravity.CENTER);if(i==27){x.setTextColor(Color.WHITE);bg(x,blue,12);}else if(i%7!=6&&i%7!=0)bg(x,Color.rgb(235,249,241),12);g.addView(x,new ViewGroup.LayoutParams(dp(45),dp(48)));}c.addView(g);c.addView(t("● Trabajado       ● Descanso       ● Extra",13,false));body.addView(c);LinearLayout sum=card();sum.addView(t("▥  Resumen del mes",17,true));sum.addView(row("📅","24 días trabajados","Horas normales: 192 h",""));sum.addView(row("◷","18 h extra","Días de descanso: 4",""));body.addView(sum);}
 void history(){shell("",2);TextView h=t("Historial",22,true);h.setGravity(Gravity.CENTER);body.addView(h);LinearLayout c=card();c.addView(t("Septiembre 2026",18,true));c.addView(row("✓","Hoy · 07:30 — 17:30","9 h trabajadas","S/ 126.40"));c.addView(row("✓","Ayer · 07:28 — 17:15","8 h 47 min","S/ 112.80"));c.addView(row("＋","25 Sep · Horas extra","2 h extra","S/ 18.45"));body.addView(c);LinearLayout s=card();s.addView(t("Resumen",17,true));s.addView(t("Ingresos estimados     S/ 3,240\nHoras normales          192 h\nHoras extra                 18 h",16,false));body.addView(s);}
 void settings(){shell("",3);TextView h=t("Mi trabajo",22,true);h.setGravity(Gravity.CENTER);body.addView(h);LinearLayout hero=card();bg(hero,Color.rgb(222,239,255),18);hero.addView(t("⛑  Configuración laboral",18,true));hero.addView(t("Personaliza los datos según tu trabajo.\nLa app se adapta a tu rubro.",13,false));body.addView(hero);LinearLayout pay=card();pay.addView(row("▣","Forma de pago","","Semanal"));pay.addView(row("💵","Sueldo / Jornal","","S/ 62.80"));pay.addView(row("◷","Horas extra","","Configurar"));body.addView(pay);LinearLayout ben=card();ben.addView(t("🎁  Beneficios (opcional)",17,true));ben.addView(toggle("Bonificación por movilidad",true));ben.addView(toggle("Viáticos",true));ben.addView(toggle("Gratificación",false));ben.addView(toggle("Vacaciones",false));body.addView(ben);LinearLayout ded=card();ded.addView(t("%  Descuentos",17,true));ded.addView(toggle("ONP (13%)",true));ded.addView(toggle("AFP / CONAF (opcional)",false));body.addView(ded);LinearLayout vari=card();vari.addView(t("ⓢ  Ingresos variables (opcional)",17,true));vari.addView(toggle("Propinas",true));vari.addView(toggle("Comisión",true));vari.addView(toggle("Bonos",false));body.addView(vari);}
 Switch toggle(String s,boolean on){Switch v=new Switch(this);v.setText(s);v.setTextSize(15);v.setTextColor(ink);v.setChecked(on);v.setPadding(dp(4),dp(7),dp(4),dp(7));return v;}
}