package pe.apptrabajador;
import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;
public class MainActivity extends Activity{
 LinearLayout content; TextView total,hours; EditText entry,exit,tips,commission; Spinner rest; int blue=Color.rgb(37,99,235),ink=Color.rgb(20,31,51),muted=Color.rgb(100,116,139);
 int dp(float v){return(int)(v*getResources().getDisplayMetrics().density+.5f);}
 void bg(View v,int c,float r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));v.setBackground(g);}
 TextView tx(String s,int z,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(ink);v.setPadding(0,dp(5),0,dp(5));if(b)v.setTypeface(null,1);return v;}
 LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(16),dp(18),dp(16));bg(c,Color.WHITE,18);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(14));c.setLayoutParams(p);return c;}
 EditText input(String s){EditText e=new EditText(this);e.setText(s);e.setTextSize(16);e.setSingleLine();e.setPadding(dp(12),dp(10),dp(12),dp(10));bg(e,Color.rgb(245,247,250),12);return e;}
 Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setTextSize(15);bg(b,blue,14);return b;}
 public void onCreate(Bundle b){super.onCreate(b);home();}
 void shell(String title){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(247,249,252));TextView h=tx(title,22,true);h.setPadding(dp(20),dp(20),dp(20),dp(12));root.addView(h);ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(18),dp(4),dp(18),dp(20));sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));LinearLayout nav=new LinearLayout(this);for(String n:new String[]{"Inicio","Calendario","Historial","Ajustes"}){Button x=new Button(this);x.setText(n);x.setAllCaps(false);x.setTextSize(12);x.setBackgroundColor(Color.TRANSPARENT);x.setOnClickListener(v->{if(n.equals("Inicio"))home();else simple(n);});nav.addView(x,new LinearLayout.LayoutParams(0,dp(58),1));}root.addView(nav);setContentView(root);}
 void home(){shell("App Trabajador");content.addView(tx("Hola 👋",28,true));TextView d=tx(new SimpleDateFormat("EEEE, d MMMM",new Locale("es","PE")).format(new Date()),14,false);d.setTextColor(muted);content.addView(d);LinearLayout c=card();c.addView(tx("Registro de hoy",18,true));LinearLayout row=new LinearLayout(this);entry=input("07:30");exit=input("17:30");row.addView(field("Entrada",entry),new LinearLayout.LayoutParams(0,-2,1));row.addView(field("Salida",exit),new LinearLayout.LayoutParams(0,-2,1));c.addView(row);c.addView(tx("Descanso",13,false));rest=new Spinner(this);rest.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"45 min","60 min","90 min"}));rest.setSelection(1);c.addView(rest);Button calc=button("Calcular mi día");calc.setOnClickListener(v->calc());c.addView(calc);content.addView(c);LinearLayout earn=card();earn.addView(tx("Ganancia estimada",15,false));total=tx("S/ 66.42",32,true);total.setTextColor(blue);earn.addView(total);hours=tx("9.00 h trabajadas",14,false);hours.setTextColor(muted);earn.addView(hours);content.addView(earn);LinearLayout vr=card();vr.addView(tx("Ingresos variables",18,true));vr.addView(tx("Propinas (S/)",13,false));tips=input("0");tips.setInputType(2|8192);vr.addView(tips);vr.addView(tx("Comisión (S/)",13,false));commission=input("0");commission.setInputType(2|8192);vr.addView(commission);Button save=button("Guardar registro");save.setOnClickListener(v->{calc();Toast.makeText(this,"Registro guardado para esta prueba",Toast.LENGTH_SHORT).show();});vr.addView(save);content.addView(vr);}
 LinearLayout field(String l,EditText e){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(0,0,dp(8),dp(12));x.addView(tx(l,13,false));x.addView(e);return x;}
 void calc(){try{String[]a=entry.getText().toString().split(":"),z=exit.getText().toString().split(":");int s=Integer.parseInt(a[0])*60+Integer.parseInt(a[1]),en=Integer.parseInt(z[0])*60+Integer.parseInt(z[1]);if(en<s)en+=1440;int br=new int[]{45,60,90}[rest.getSelectedItemPosition()];double h=Math.max(0,en-s-br)/60.0,p=h*7.38+num(tips)+num(commission);hours.setText(String.format(Locale.US,"%.2f h trabajadas",h));total.setText(String.format(Locale.US,"S/ %.2f",p));}catch(Exception e){Toast.makeText(this,"Revisa las horas ingresadas",Toast.LENGTH_SHORT).show();}}
 double num(EditText e){try{return Double.parseDouble(e.getText().toString());}catch(Exception x){return 0;}}
 void simple(String n){shell(n);LinearLayout c=card();c.addView(tx(n,24,true));c.addView(tx(n.equals("Calendario")?"Aquí aparecerán tus días trabajados, descansos y horas extra.":n.equals("Historial")?"Tus registros diarios y pagos aparecerán aquí.":"Configura sueldo, jornal, horario, horas extra y conceptos de pago.",16,false));content.addView(c);}
}
